server:
  port: 10086
spring:
  application:
    name: haku-eureka #作为微服务名称注入到eureka容器

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  server:
    eviction-interval-timer-in-ms: 5000 # 扫描失效服务的间隔时间，默认60秒
    enable-self-preservation: false # 关闭自我保护模式，当服务挂掉时，立即剔除 默认为true