server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/youngbor?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: haku-provider # 将来会作为微服务的名称
# mybatis包的扫描，还有就是映射文件设置 mybatis tk插件的使用
mybatis:
  type-aliases-package: com.haku.project.entity
  mapper-locations: classpath*:mapper/*.xml
  #配置驼峰下划线
  configuration:
      map-underscore-to-camel-case: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15  # 服务失效时间，默认为90秒 过期时间
    lease-renewal-interval-in-seconds: 5 # 服务续约（renew）的间隔时间，默认为30秒 心跳时间